### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by musahi0128** [divyam234/teldrive#17]
Hi, I am following the guide on the main page but unable to upload. Every time I tried this error shows and it did not tell me what's wrong.
![3277TLzsni](https://github.com/divyam234/teldrive/assets/9418340/9d7ddda4-8fde-4fad-bea0-c8adc6b07d19)
I get a minus channel id so I tried both using minus and without minus, and both still failed to upload.
The channel type is private and there is only my account listed as user in it.
Here's my .env
```
APP_ID=2496
APP_HASH=8da85b0d5bfe62527e5b244c209159c3
CHANNEL_ID=REDACTED
HTTPS=false
COOKIE_SAME_SITE=true
JWT_SECRET=gbT9iovNfvGGo4S1C2+r7Phwh9qXPVIJdLpRJxpO44I=
DATABASE_URL=postgres://REDACTED:REDACTED@ep-summer-shadow-51097936.us-east-2.aws.neon.tech/neondb
RATE_LIMIT=true
TG_CLIENT_DEVICE_MODEL="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203" # Any valid  browser user agent here
TG_CLIENT_SYSTEM_VERSION=Win32
TG_CLIENT_APP_VERSION=2.1.9 K
TG_CLIENT_LANG_CODE=en
TG_CLIENT_SYSTEM_LANG_CODE=en
TG_CLIENT_LANG_PACK=webk
MULTI_CLIENT=false
MULTI_TOKEN1=55838383:yourfirstmulticlientbottokenhere
MULTI_TOKEN2=55838383:yoursecondmulticlientbottokenhere
MULTI_TOKEN3=55838383:yourthirdmulticlientbottokenhere
```
I access the apps from http://localhost:8000
And here's the setting's page
![tvnviewer_JhEalMCmZz](https://github.com/divyam234/teldrive/assets/9418340/f05ab642-eec7-467d-9c37-5274cb3c09a6)
I assume I have to put http://localhost:8000 on API URL, but with or without putting value on that field, the upload still failed.
Thanks!

**Comment by divyam234** [comment]
@musahi0128  Can you join post docker logs  here

**Comment by musahi0128** [comment]
Hi, sorry but I don't know what to do. What file do I need to get you ?

**Comment by Wargasmz** [comment]
@musahi0128 must be the channel id, if started with -100 remove minus and the 100 also.

To see logs errors run the command
sudo docker logs server -f

In the setting's page you can leave it blank.

**Comment by musahi0128** [comment]
Hi, yes, the channel ID is -1001910318059. Putting it as 1910318059 didn't change anything.
Here's output of docker logs server -f
```
[150/204]2023/08/28 01:14:40 goose: no migrations to run. current version: 20230820014560                                      [GIN] 2023/08/28 - 01:22:44 | 200 |    6.114733ms |      172.26.0.4 | GET      "/api/auth/session"                    2023/08/28 01:23:06 net/http: invalid Cookie.Domain "localhost:8000"; dropping domain attribute                       [GIN] 2023/08/28 - 01:23:06 | 200 |  1.135395737s |      172.26.0.4 | POST     "/api/auth/login"                      2023/08/28 01:23:07 websocket: close 1001 (going away)
[GIN] 2023/08/28 - 01:23:07 | 200 | 21.444607088s |      17
2.26.0.4 | GET      "/api/auth/ws"
[GIN] 2023/08/28 - 01:23:08 | 200 |  175.758695ms |      17
2.26.0.4 | GET      "/api/auth/session"
2023/08/28 01:23:08 net/http: invalid Cookie.Domain "localh
ost:8000"; dropping domain attribute                       panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x136ab70]                                              
goroutine 229 [running]:
github.com/divyam234/teldrive/services.(*UserService).GetPr
ofilePhoto.func1({0xc000061f28?, 0xc000061f00?})
        /app/services/user.service.go:73 +0xb0             github.com/gotd/td/telegram.(*Client).Run.func3({0x1adfc28, 0xc00051ae60})                                                    /go/pkg/mod/github.com/gotd/td@v0.84.0/telegram/connect.go:150 +0xb7                                          github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6()
github.com/gotd/td/telegram.(*Client).Run.(*Cancel[121/204]
p).Go.func6()                                                      /go/pkg/mod/github.com/gotd/td@v0.84.0/internal/tdsync/cancel_group.go:48 +0x26                               golang.org/x/sync/errgroup.(*Group).Go.func1()                     /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56                                            created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 146                                                            /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96                                            2023/08/28 01:23:11 goose: no migrations to run. current version: 20230820014560                                      [GIN] 2023/08/28 - 01:23:12 | 404 |  147.352458ms |      172.26.0.4 | GET      "/api/files?nextPageToken=&perPage=200&order=desc&path=%2F&sort=name&view=my-drive"               Error #01: This directory doesn't exist.
panic: runtime error: invalid memory address or nil pointer
 dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18
pc=0x136ab70]

goroutine 121 [running]:                                   github.com/divyam234/teldrive/services.(*UserService).GetProfilePhoto.func1({0xc000510728?, 0xc000510700?})
        /app/services/user.service.go:73 +0xb0             github.com/gotd/td/telegram.(*Client).Run.func3({0x1adfc28,
 0xc00052e780})
        /go/pkg/mod/github.com/gotd/td@v0.84.0/telegram/con
nect.go:150 +0xb7
github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6()                                      [90/204]
        /go/pkg/mod/github.com/gotd/td@v0.84.0/internal/tds
ync/cancel_group.go:48 +0x26
golang.org/x/sync/errgroup.(*Group).Go.func1()                     /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 117
        /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgr
oup.go:72 +0x96
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 25 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b                 created by github.com/divyam234/teldrive/database.InitDB in goroutine 1                                                       /app/database/database.go:57 +0x4d9                panic: ERROR: relation "goose_db_version" already exists (SQLSTATE 42P07)                                                                                                        goroutine 25 [running]:                                    github.com/divyam234/teldrive/database.migrate()                   /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b                 created by github.com/divyam234/teldrive/database.InitDB in
 goroutine 1
/app/database/database.go:57 +0x4d9                panic: ERROR: relation "goose_db_version" already exists (SQLSTATE 42P07)                                                                                                        goroutine 26 [running]:
github.com/divyam234/teldrive/database.migrate()                   /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b                 created by github.com/divyam234/teldrive/database.InitDB in goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 9 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b
created by github.com/divyam234/teldrive/database.InitDB in goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 39 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd
github.com/divyam234/teldrive/database.InitDB.func2()
/app/database/database.go:60 +0x3b
created by github.com/divyam234/teldrive/database.InitDB in goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 36 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd
github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b
created by github.com/divyam234/teldrive/database.InitDB in
 goroutine 1                                                       /app/database/database.go:57 +0x4d9                panic: ERROR: relation "goose_db_version" already exists (SQLSTATE 42P07)

goroutine 50 [running]:                                    github.com/divyam234/teldrive/database.migrate()                   /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b                 created by github.com/divyam234/teldrive/database.InitDB in
 goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)
goroutine 10 [running]:
github.com/divyam234/teldrive/database.migrate()                   /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b                 created by github.com/divyam234/teldrive/database.InitDB in goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 20 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd                 github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b
created by github.com/divyam234/teldrive/database.InitDB in goroutine 1
        /app/database/database.go:57 +0x4d9
panic: ERROR: relation "goose_db_version" already exists (S
QLSTATE 42P07)

goroutine 11 [running]:
github.com/divyam234/teldrive/database.migrate()
        /app/database/database.go:75 +0xdd
github.com/divyam234/teldrive/database.InitDB.func2()              /app/database/database.go:60 +0x3b
created by github.com/divyam234/teldrive/database.InitDB in
 goroutine 1
/app/database/database.go:57 +0x4d9
```
I'm sorry if it a bit messed up, I'm copying it from termux so please bear with me.
I see some mention about database, but even with empty one the issue persists.
Thanks!

**Comment by divyam234** [comment]
@musahi0128 try so  create new database delete the current one you are using its says migration db table already exists so just create a whole new instance of datbase or clear all  tables from all  schema

**Comment by musahi0128** [comment]
I'll do that. But before going further, any way I can redirect the log to a file? I guess it will be better instead of me copy paste the terminal output.

**Comment by musahi0128** [comment]
I manage to get your apps working.
- I am using a brand-new database
- I used "Deploy using docker-compose" instruction
- I modify the docker-compose.yml as follow:
```
version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive/server:latest
    restart: always
    container_name: server
    volumes:
      - ./sessions:/app/sessions:rw
      - ./database:/app/database
    env_file: .env
    ports:
      - "127.0.0.3:8080:8080"

  client:
    image: ghcr.io/divyam234/teldrive/client:latest
    restart: always
    container_name: client
    ports:
      - "127.0.0.3:3000:3000"

  haproxy:
    image: haproxy:latest
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    # ports:
    #   - 80:80
    #   - 443:443
    ports:
      - "127.0.0.3:8000:8000"
    depends_on:
     - server
     - client
```
Notice that I'm putting localhost IP address. My guess is that the issue with my previous attempt was the port is all over the place and get assigned 0.0.0.0
- I uploaded jpg, mp4, txt and pdf file. All of the uploads went through now, and the file is sent to the correct Telegram channel (-100 stripped from original channel id)
- All of the previously uploaded files can be downloaded without any problem.

Minor issue
- I tried to preview all of the files and only pdf preview is failed
![msedge_jwcOU8yVW6](https://github.com/divyam234/teldrive/assets/9418340/681291a5-35f5-403d-a5fb-bcc7cc8f374c)
- Drag and drop is not supported

I hope my struggle and experience can be useful for someone else.
Thank you for your great apps and your kind support. Cheers!
