### ISSUE TITLE
Uploud error

### ISSUE THREAD

**Issue by PLoliwi** [divyam234/teldrive#199]
interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
goroutine 524 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1898 +0xbe
panic({0x17c41c0?, 0xc001162090?})
	runtime/panic.go:770 +0x132
github.com/divyam234/teldrive/pkg/services.getParts({0x2171c08, 0xc0000e8f00}, 0xc000fef408, 0xc001230690, {0xc0003caf46, 0xa})
	github.com/divyam234/teldrive/pkg/services/common.go:162 +0x531
github.com/divyam234/teldrive/pkg/services.(*FileService).GetFileStream(0xc00002a198, 0xc0000e8f00)
	github.com/divyam234/teldrive/pkg/services/file.go:536 +0x143e
github.com/divyam234/teldrive/pkg/controller.(*Controller).GetFileStream(...)
	github.com/divyam234/teldrive/pkg/controller/file.go:184
github.com/gin-gonic/gin.(*Context).Next(...)
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/divyam234/teldrive/cmd.initApp.func1(0xc0000e8f00)
	github.com/divyam234/teldrive/cmd/run.go:226 +0x1a3
github.com/gin-gonic/gin.(*Context).Next(0xc0000e8f00)
	github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/divyam234/teldrive/cmd.initApp.GinzapWithConfig.func4(0xc0000e8f00)
	github.com/gin-contrib/zap@v1.1.1/zap.go:68 +0xb1
github.com/gin-gonic/gin.(*Context).Next(...)
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001b8820, 0xc0000e8f00)
	github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001b8820, {0x216edf8, 0xc0006c08c0}, 0xc001109b00)
	github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1b2
net/http.serverHandler.ServeHTTP({0xc001113b30?}, {0x216edf8?, 0xc0006c08c0?}, 0x6?)
	net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc001110e10, {0x21719d8, 0xc000436720})
	net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 67
	net/http/server.go:3285 +0x4b4

**Comment by PLoliwi** [comment]
@divyam234 
How to fix?

**Comment by PLoliwi** [comment]
21/04/2024 01:51 PM	ERROR	[DB] github.com/divyam234/teldrive/pkg/services/user.go:117 ERROR: null value in column "channel_id" of relation "channels" violates not-null constraint (SQLSTATE 23502)
[68.779ms] [rows:0] INSERT INTO "teldrive"."channels" ("channel_name","user_id","selected") VALUES ('',6308911861,true) ON CONFLICT ("channel_id") DO UPDATE SET "selected"=true RETURNING "channel_id"

**Comment by PLoliwi** [comment]
Fix Good

**Comment by PLoliwi** [comment]
You can delete the thread

**Comment by PLoliwi** [comment]
@divyam234
