### ISSUE TITLE
Version 1.4.10 Database connection error

### ISSUE THREAD

**Issue by SingingDalong** [divyam234/teldrive#298]
I used version 1.4.10. The database uses PostgreSQL. However, the following error appears. It seems to be incompatible with the existing.
```
M:\Programs_1\teldrive-windows-amd64>teldrive run
panic: failed run migrate: ERROR 20240711163538_search.sql: failed to run SQL migration: failed to execute SQL query "CREATE EXTENSION IF NOT EXISTS pgroonga;\nDROP INDEX IF EXISTS teldrive.name_search_idx;\nDROP FUNCTION IF EXISTS  teldrive.get_tsquery;\nDROP FUNCTION IF EXISTS teldrive.get_tsvector;\nCREATE INDEX name_search_idx ON teldrive.files USING pgroonga (REGEXP_REPLACE(name, '[.,-_]', ' ', 'g')) WITH (tokenizer = 'TokenNgram');": 오류: "pgroonga" 이름의 확장 모듈을
사용할 수 없습니다 (SQLSTATE 0A000)

goroutine 1 [running]:
github.com/divyam234/teldrive/internal/database.NewDatabase(0xc000121800)
        github.com/divyam234/teldrive/internal/database/database.go:63 +0x4cb
reflect.Value.call({0x1c7a360?, 0x252ae90?, 0x4b4cce38?}, {0x20213d3, 0x4}, {0xc00002c420, 0x1, 0x4b4c0b48?})
        reflect/value.go:596 +0xca6
reflect.Value.Call({0x1c7a360?, 0x252ae90?, 0x8626e5?}, {0xc00002c420?, 0x1dcd6a0?, 0xc000341901?})
        reflect/value.go:380 +0xb9
go.uber.org/dig.defaultInvoker({0x1c7a360?, 0x252ae90?, 0xc00037c360?}, {0xc00002c420?, 0x1?, 0x273abf0?})
        go.uber.org/dig@v1.17.1/container.go:238 +0x25
go.uber.org/dig.(*constructorNode).Call(0xc0000c2540, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/constructor.go:185 +0x34a
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x2742d68, 0x200d980}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x2742d68, 0x1ce9620}, {0xc00006dec0, 0x4, 0x4}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*constructorNode).Call(0xc0000c29c0, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/constructor.go:155 +0x137
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x2742d68, 0x1f375e0}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x2742d68, 0x1ce95c0}, {0xc00023e700, 0x4, 0x4}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*constructorNode).Call(0xc0000c2c00, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/constructor.go:155 +0x137
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x2742d68, 0x1fdd0a0}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x2742d68, 0x1d1c620}, {0xc0002462d0, 0x5, 0x5}}, {0x273abf0, 0xc000022500})
        go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*Scope).Invoke(0xc000022500, {0x1d1c620, 0x252ae78}, {0x0, 0x0, 0x360d380?})
        go.uber.org/dig@v1.17.1/invoke.go:122 +0x318
go.uber.org/dig.(*Container).Invoke(0x20?, {0x1d1c620?, 0x252ae78?}, {0x0?, 0xc0002eea80?, 0xc00051d6a0?})
        go.uber.org/dig@v1.17.1/invoke.go:82 +0x25
go.uber.org/fx.runInvoke({0x4b5088e8?, 0xc000014128?}, {{0x1d1c620, 0x252ae78}, {0xc00028e640, 0x7, 0x8}})
        go.uber.org/fx@v1.22.1/invoke.go:109 +0x153
go.uber.org/fx.(*module).executeInvoke(0xc0002bc340, {{0x1d1c620, 0x252ae78}, {0xc00028e640, 0x7, 0x8}})
        go.uber.org/fx@v1.22.1/module.go:320 +0x145
go.uber.org/fx.(*module).executeInvokes(0xc0002bc340)
        go.uber.org/fx@v1.22.1/module.go:306 +0xda
go.uber.org/fx.New({0xc00051db08, 0x7, 0x0?})
        go.uber.org/fx@v1.22.1/app.go:517 +0x9fa
github.com/divyam234/teldrive/cmd.runApplication(0xc000121800)
        github.com/divyam234/teldrive/cmd/run.go:133 +0x617
github.com/divyam234/teldrive/cmd.NewRun.func1(0xc00026c600?, {0x2021337?, 0x4?, 0x202133b?})
        github.com/divyam234/teldrive/cmd/run.go:47 +0x17
github.com/spf13/cobra.(*Command).execute(0xc000123208, {0x36c5280, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000122f08)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(0x2718900?, {0x2718ac0?, 0xc000787680?})
        github.com/spf13/cobra@v1.8.1/command.go:1034 +0x47
main.main()
        ./main.go:15 +0x96
```

**Comment by divyam234** [comment]
@SingingDalong  Read release notes carefully

**Comment by SingingDalong** [comment]
> @SingingDalong 릴리스 노트를 주의 깊게 읽으세요
Thank you. Solved after PGroonga patch.

**Comment by Pe0xonN** [comment]
> > @SingingDalong 릴리스 노트를 주의 깊게 읽으세요
> > Thank you. Solved after PGroonga patch. And Korean searches work well too.

 How did you do it?

**Comment by SingingDalong** [comment]
> > > @SingingDalong 릴리스 노트를 주의 깊게 읽으세요
> > > Thank you. Solved after PGroonga patch. And Korean searches work well too.
> 
> How did you do it?
https://pgroonga.github.io/install/windows.html
I downloaded and patched the PGroonga package that can be used for PostgreSQL from the link above.

**Comment by Pe0xonN** [comment]
> > How did you do it?
> > https://pgroonga.github.io/install/windows.html
> > I downloaded and patched the PGroonga package that can be used for PostgreSQL from the link above.


Neon tech db?

**Comment by Pe0xonN** [comment]
> 
> Neon DB cannot be used. You must use PostgreSQL(https://www.postgresql.org).


what about the data
