### ISSUE TITLE
divyam234/rclone: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by steffen-poulsen** [divyam234/teldrive#65]
divyam234/rclone threw this nil pointer error after me recently, not sure if it is of interest, after getting some `socket: too many open files`, i.e. `low level retry 10/10 (error Get "http://192.168.1.xxx:8080/api/uploads/xxx": dial tcp 192.168.1.xxx:8080: socket: too many open files)` errors.

I haven't set any ulimit options for the containers, not sure if it is needed.

I'll just leave the strack trace here - note that the error appears to be with rclone, and not teldrive.

And thank you for a most useful tool! :-)

```
2023/11/25 15:35:25 DEBUG : pacer: low level retry 10/10 (error Get "http://192.168.1.xxx:8080/api/files?name=<....>": dial tcp 192.168.1.xxx:8080: socket: too many open files)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1886a1a]

goroutine 102 [running]:
github.com/rclone/rclone/backend/teldrive.(*Fs).findObject(0xc0005ac2d0, {0x27f9da8?, 0xc000e223c0}, {0xc003da60c0, 0x3d}, {0xc00743e0bd, 0x37})
        github.com/rclone/rclone/backend/teldrive/teldrive.go:395 +0x43a
github.com/rclone/rclone/backend/teldrive.(*Fs).NewObject(0xc0005ac2d0, {0x27f9da8, 0xc000e223c0}, {0xc003cafd50, 0x6d})
        github.com/rclone/rclone/backend/teldrive/teldrive.go:484 +0x59
github.com/rclone/rclone/fs/operations.multiThreadCopy({0x27f9da8?, 0xc000e223c0}, {0x280e448, 0xc0005ac2d0}, {0xc003cafd50, 0x6d}, {0x280c0d8?, 0xc001b0b500}, 0x4, 0xc0071ba140, ...)
        github.com/rclone/rclone/fs/operations/multithread.go:237 +0xf31
github.com/rclone/rclone/fs/operations.(*copy).multiThreadCopy(0xc00795ee10, {0x27f9da8?, 0xc000e223c0?}, {0xc002db9620?, 0x280c0d8?, 0xc001b0b500?})
        github.com/rclone/rclone/fs/operations/copy.go:160 +0x85
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc00795ee10, {0x27f9da8, 0xc000e223c0})
        github.com/rclone/rclone/fs/operations/copy.go:249 +0x425
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc00795ee10, {0x27f9da8, 0xc000e223c0})
        github.com/rclone/rclone/fs/operations/copy.go:302 +0x16c
github.com/rclone/rclone/fs/operations.Copy({0x27f9da8, 0xc000e223c0}, {0x280e448, 0xc0005ac2d0}, {0x0?, 0x0}, {0xc003cafd50, 0x6d}, {0x280c0d8, 0xc001b0b500})
        github.com/rclone/rclone/fs/operations/copy.go:404 +0x425
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000a28b40, {0x27f9da8, 0xc000e223c0}, 0x0?, {0x280e448, 0xc0005ac2d0}, 0x0?, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:446 +0x1f6
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:473 +0x45

# rclone --version
rclone v1.64.3
- os/version: unknown
- os/kernel: 4.4.302+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.4
- go/linking: static
- go/tags: none
```

**Comment by ben-ba** [comment]
seems "normal" when you try to upload many small files, after a amount of x hours this nil pointer is thrown.

**Comment by steffen-poulsen** [comment]
I raised the ulimit and I have not seen the error since. Closing this.
